build:
  nodes:
    coverage-tests:
      tests:
        override:
          - command: phpunit --coverage-clover=coverage.txt
            coverage:
              file: coverage.txt
              format: php-clover
