build:
  nodes:
    my-tests-with-coverage:
      tests:
        override:
          - command: phpunit --coverage-clover=coverage.txt
            coverage:
              file: coverage.clover
              format: php-clover
